site_name: 工高班资料汇总
site_url: https://github.com/ZJU-ACEE/Archive/
site_description: 工高班资料汇总
repo_name: ZJU-ACEE/Archive
repo_url: https://github.com/ZJU-ACEE/Archive/
edit_uri: tree/master/docs
copyright: Copyright &copy; 2024 浙江大学工程教育高级班

nav:
  - 主页:
    - index.md
  - 班级档案:
    - class/index.md

  - 个人档案:
    - person/index.md

  - 学长学姐说:
    - interview/index.md
    - 刘芃骐: interview/PengqiLiu/index.md
    - 周晨旭: interview/ChenxuZhou/index.md
    - 张成鹍: interview/ChengkunZhang/index.md
    - 梁艺馨: interview/YixinLiang/index.md
    - 滕佳琪: interview/JiaqiTeng/index.md
    - 陈佳禾: interview/JiaHeChen/index.md

  - 班级相册:
    - album/index.md
    - 破冰活动: album/icebreak/index.md

theme:
  name: 'material'
  language: 'zh'
  icon:
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  favicon: images/icon.jpg
  custom_dir: overrides
  features:
  - content.code.annotate
  - content.action.edit
  - navigation.tracking
  - navigation.top
  - navigation.tabs
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  font:
    code: JetBrains Mono
  palette:
    - scheme: default
  
plugins:
  - search
  - toc
  - heti:
      extra_skipped_class:
        - arithmatex
  - encryptcontent:
      title_prefix: ""
      summary: ''
      placeholder: '在此输入密码'
      encryption_info_message: '请输入密码'
      remember_password: True 
      default_expire_dalay: 48
      decryption_failure_message: '密码错误'
      global_password: 'ACEE2024'

  # - turing_changelog
  # - turing_contributors
  # - turing_evaluations
  # - turing_outdate_warning

extra_css:
  - https://fonts.googleapis.com/css?family=Noto+Serif+SC:300,300i,400,400i,700,700i&display=fallback
  - css/tasklist.css
  - css/card.css
  - css/custom.css

extra_javascript:
  - js/katex.js

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
